### ISSUE TITLE
armor makes no mention of fallen kings crown as a possible option

### ISSUE THREAD

**Issue by walksanatora** [myaltaccountsthis/arcane-odyssey-guides#10]

**Comment by myaltaccountsthis** [comment]
King Mantello takes priority over the crown due to it coming first in the info file. Because the stats are the same, you can switch them out with each other. Currently, King Crown only appears if both accessories are necessary.
![image](https://github.com/myaltaccountsthis/arcane-odyssey-guides/assets/71832770/38818070-8f35-40e8-abf8-84af0bf5a6d2)
